In [43]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [44]:
# Importing the dataset
dataset = pd.read_csv('winequality-red.csv')
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [45]:
dataset.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.256131     0.671703   
volatile acidity          -0.256131          1.000000    -0.552496   
citric acid                0.671703         -0.552496     1.000000   
residual sugar             0.114777          0.001918     0.143577   
chlorides                  0.093705          0.061298     0.203823   
free sulfur dioxide       -0.153794         -0.010504    -0.060978   
total sulfur dioxide      -0.113181          0.076470     0.035533   
density                    0.668047          0.022026     0.364947   
pH                        -0.682978          0.234937    -0.541904   
sulphates                  0.183006         -0.260987     0.312770   
alcohol                   -0.061668         -0.202288     0.109903   
quality                    0.124052         -0.390558     0.226373   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.114777   0.093705            -0.153794   
volatile acidity            0.001918   0.061298            -0.010504   
citric acid                 0.143577   0.203823            -0.060978   
residual sugar              1.000000   0.055610             0.187049   
chlorides                   0.055610   1.000000             0.005562   
free sulfur dioxide         0.187049   0.005562             1.000000   
total sulfur dioxide        0.203028   0.047400             0.667666   
density                     0.355283   0.200632            -0.021946   
pH                         -0.085652  -0.265026             0.070377   
sulphates                   0.005527   0.371260             0.051658   
alcohol                     0.042075  -0.221141            -0.069408   
quality                     0.013732  -0.128907            -0.050656   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.113181  0.668047 -0.682978   0.183006   
volatile acidity                  0.076470  0.022026  0.234937  -0.260987   
citric acid                       0.035533  0.364947 -0.541904   0.312770   
residual sugar                    0.203028  0.355283 -0.085652   0.005527   
chlorides                         0.047400  0.200632 -0.265026   0.371260   
free sulfur dioxide               0.667666 -0.021946  0.070377   0.051658   
total sulfur dioxide              1.000000  0.071269 -0.066495   0.042947   
density                           0.071269  1.000000 -0.341699   0.148506   
pH                               -0.066495 -0.341699  1.000000  -0.196648   
sulphates                         0.042947  0.148506 -0.196648   1.000000   
alcohol                          -0.205654 -0.496180  0.205633   0.093595   
quality                          -0.185100 -0.174919 -0.057731   0.251397   

                       alcohol   quality  
fixed acidity        -0.061668  0.124052  
volatile acidity     -0.202288 -0.390558  
citric acid           0.109903  0.226373  
residual sugar        0.042075  0.013732  
chlorides            -0.221141 -0.128907  
free sulfur dioxide  -0.069408 -0.050656  
total sulfur dioxide -0.205654 -0.185100  
density              -0.496180 -0.174919  
pH                    0.205633 -0.057731  
sulphates             0.093595  0.251397  
alcohol               1.000000  0.476166  
quality               0.476166  1.000000

In [46]:
X = dataset.iloc[:,:11].values
y = dataset.iloc[:, 11:12].values
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [47]:
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [48]:
y

array([[5],
       [5],
       [5],
       ...,
       [6],
       [5],
       [6]], dtype=int64)

In [49]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size = 0.2, random_state = 0)

In [50]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [51]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [52]:
y_pred = regressor.predict(X_test)

In [53]:
y_pred

array([[5.7829301 ],
       [5.03619267],
       [6.59698929],
       [5.33912637],
       [5.93952898],
       [5.0072068 ],
       [5.39616171],
       [6.05211188],
       [4.86760343],
       [4.95067572],
       [5.28580441],
       [5.41265269],
       [5.7057424 ],
       [5.12921737],
       [5.52885206],
       [6.38052412],
       [6.81012527],
       [5.73803346],
       [5.97618825],
       [5.08613415],
       [6.34479863],
       [5.16400983],
       [5.64203971],
       [6.1462903 ],
       [5.4817802 ],
       [5.03391406],
       [5.18721293],
       [6.48783659],
       [5.33301372],
       [6.30458308],
       [6.03452293],
       [5.82849303],
       [5.58503524],
       [5.28512701],
       [5.75656128],
       [6.15273792],
       [5.14134479],
       [5.48228021],
       [6.38983359],
       [5.7901819 ],
       [5.42936928],
       [6.04810414],
       [6.70159678],
       [6.60160183],
       [5.97253803],
       [4.78890763],
       [5.49565005],
       [6.018

In [54]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators= 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train,y_train)

<ipython-input-54-a7552030339f>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [55]:
y_rpred = classifier.predict(X_test)

In [56]:
y_rpred

array([6, 5, 7, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 7, 5, 5, 5, 7, 5,
       6, 6, 6, 5, 5, 7, 5, 7, 6, 5, 6, 5, 7, 7, 5, 6, 6, 6, 5, 6, 7, 7,
       6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 7, 5, 5, 5, 5, 6, 5, 6,
       5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 5, 5, 7, 6, 6, 6, 5, 6, 5, 6, 5,
       6, 5, 5, 5, 6, 6, 6, 5, 7, 5, 5, 5, 7, 6, 5, 7, 5, 5, 5, 5, 6, 5,
       6, 5, 6, 5, 6, 6, 5, 7, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5, 6, 7, 6, 5,
       6, 6, 6, 5, 6, 5, 7, 5, 6, 5, 5, 5, 5, 6, 6, 6, 7, 5, 5, 5, 5, 5,
       6, 6, 5, 5, 6, 6, 6, 5, 7, 5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 7, 5, 6,
       6, 7, 7, 5, 5, 6, 5, 6, 7, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 5, 5, 5, 7, 6, 6, 6, 6, 5, 6, 5, 6, 5, 7, 6, 6,
       5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 7, 7, 6, 6, 5,
       5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 7, 5, 6, 5, 6,
       5, 5, 5, 5, 6, 6, 5, 5, 5, 6, 7, 6, 7, 6, 6, 7, 5, 7, 5, 6, 6, 5,
       5, 5, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6,

In [57]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_rpred)

In [58]:
cm

array([[  0,   0,   1,   1,   0,   0],
       [  0,   0,   7,   4,   0,   0],
       [  0,   0, 112,  20,   3,   0],
       [  0,   0,  38,  91,  13,   0],
       [  0,   0,   1,  11,  15,   0],
       [  0,   0,   0,   0,   3,   0]], dtype=int64)

In [59]:
from sklearn import metrics
print('accuracy' , metrics.accuracy_score(y_rpred,y_test))

accuracy 0.68125
